### ISSUE TITLE
DateTime Generators

### ISSUE THREAD

**Issue by jcornaz** [jcornaz/kwik#6]
It would be nice to have generators for the most common types of `java.time` api (instant, zone, localDate, localTime, localDateTime, etc.)

It would obviously be available only for the JVM.

**Comment by alvaroReina** [comment]
Hi, I would like to work on this issue. Could you please check my current progress (#181) to check if I understood it correctly?

**Comment by jcornaz** [comment]
Hi @alvaroReina.

Yes it seems like a good start, and sound exactly like what I had in mind.

Just focus on the Java 8 API. So you can remove the generator for `Date` (which is the old version of `Instant`)

**Comment by alvaroReina** [comment]
Thank you very much for guiding me through my first PR. I forgot to remove the resolve issue action from the pull request, sorry about that.

As commented, I'll add the remaining types (Period, LocalDate, LocalDateTime), let me know if there are more interesting types that should be included.

This time around I will try to work on my own and open a merge request when I have it ready to be reviewed.

**Comment by jcornaz** [comment]
Thanks to you @alvaroReina.

I created a follow up issue for the remaining java time types: #192 

But I think that support for the Kotlin multiplatform time API is somewhat more appealing: #193
